### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by wdlkmpx** [wader/gtktetris#11]
Years ago I used to play Tetris at https://tetrisfriends.com/ and Tetris Battle at Facebook (the same game).

I noticed a similar game can be found at tetris.com.

The keys in GtkTetris are mostly OK, except the Down arrow key with the hard drop.

I guess this image can be used in the Help dialog and the keys can be adjusted accordingly.
![tetris_keys](https://user-images.githubusercontent.com/10052849/102033357-311a7a00-3df6-11eb-8b84-6ee730a6826f.png)

HOLD - C is probably not implemented.

**Comment by wader** [comment]
Yes seem like a good ideas

Haven't heard about hold before. Would that be something configurable or just have it enabled always and just up to the player to use or not?
