### ISSUE TITLE
Build system

### ISSUE THREAD

**Issue by wdlkmpx** [wader/gtktetris#5]
A build system would benefit the project greatly.

Something that works in old and new distros without the need of updates ... autotools perhaps.

To keep things in order, the source files should be moved to a new dir src/

**Comment by wader** [comment]
Both ideas some resonable to me, not sure why i didn't use autotools for the project

**Comment by wdlkmpx** [comment]
Well it's quite easy for me to add autotools, I'll do it one of these days

**Comment by wader** [comment]
Sounds good
