### ISSUE TITLE
Change License to ISC or MIT

### ISSUE THREAD

**Issue by wdlkmpx** [wader/gtktetris#9]
I suggest changing the License to ISC or MIT.

https://opensource.org/licenses/ISC

If you agree with this, I can add a new LICENSE file and update the readme.

**Comment by wader** [comment]
Fine with me. I usually use MIT for my projects now a days. Any particular reason you want to change?

**Comment by wdlkmpx** [comment]
Nowadays most people prefer permissive licenses. I tend to reuse the
same code I write in several projects, so I think it's better to have
some permissive license.

Permissive licenses attract more developers, specially from the BSD's,
macOS.. and Windows perhaps.

My favorite license is the Unlicense, it's a bit extreme for most
people, but MIT or ISC are ok.

I'll change it to MIT then.

**Comment by wader** [comment]
👍
